# .goreleaser.yml for twelvedata-exporter

project_name: twelvedata-exporter
version: 2

# Distribution directory
dist: tmp/dist

# Build destination
github_urls:
  # set to true if you use a self-signed certificate
  skip_tls_verify: false

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - main: cmd/main.go
    id: twelvedata-exporter
    binary: twelvedata-exporter
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
    ldflags:
      - -s -w -X 'github.com/umatare5/twelvedata-exporter/cli.version={{ .Version }}'

archives:
  - name_template: '{{ .ProjectName }}-v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - "*.go"
      - "*.md"
      - "go.mod"
      - "go.sum"
      - "LICENSE"

# Docker configuration
dockers:
  - image_templates:
      - "ghcr.io/umatare5/twelvedata-exporter:latest-amd64"
      - "ghcr.io/umatare5/twelvedata-exporter:{{ .Tag }}-amd64"
      - "ghcr.io/umatare5/twelvedata-exporter:v{{ .Major }}-amd64"
      - "ghcr.io/umatare5/twelvedata-exporter:v{{ .Major }}.{{ .Minor }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Prometheus Exporter for Twelve Data"
      - "--label=org.opencontainers.image.url=https://github.com/umatare5/twelvedata-exporter"
      - "--label=org.opencontainers.image.source=https://github.com/umatare5/twelvedata-exporter"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
    goarch: amd64
    ids:
      - twelvedata-exporter
  - image_templates:
      - "ghcr.io/umatare5/twelvedata-exporter:latest-arm64"
      - "ghcr.io/umatare5/twelvedata-exporter:{{ .Tag }}-arm64"
      - "ghcr.io/umatare5/twelvedata-exporter:v{{ .Major }}-arm64"
      - "ghcr.io/umatare5/twelvedata-exporter:v{{ .Major }}.{{ .Minor }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Prometheus Exporter for Twelve Data"
      - "--label=org.opencontainers.image.url=https://github.com/umatare5/twelvedata-exporter"
      - "--label=org.opencontainers.image.source=https://github.com/umatare5/twelvedata-exporter"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
    goarch: arm64
    ids:
      - twelvedata-exporter

# Docker manifest for multi-platform images
docker_manifests:
  - name_template: "ghcr.io/umatare5/twelvedata-exporter:latest"
    image_templates:
      - "ghcr.io/umatare5/twelvedata-exporter:latest-amd64"
      - "ghcr.io/umatare5/twelvedata-exporter:latest-arm64"
  - name_template: "ghcr.io/umatare5/twelvedata-exporter:{{ .Tag }}"
    image_templates:
      - "ghcr.io/umatare5/twelvedata-exporter:{{ .Tag }}-amd64"
      - "ghcr.io/umatare5/twelvedata-exporter:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/umatare5/twelvedata-exporter:v{{ .Major }}"
    image_templates:
      - "ghcr.io/umatare5/twelvedata-exporter:v{{ .Major }}-amd64"
      - "ghcr.io/umatare5/twelvedata-exporter:v{{ .Major }}-arm64"
  - name_template: "ghcr.io/umatare5/twelvedata-exporter:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/umatare5/twelvedata-exporter:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/umatare5/twelvedata-exporter:v{{ .Major }}.{{ .Minor }}-arm64"

release:
  prerelease: auto
  draft: false
  replace_existing_draft: true
  header: |
    ## {{ .ProjectName }} v{{ .Version }}

    This release contains the Prometheus Exporter for Twelve Data.

    ### 🐳 Container Images

    ```bash
    # Latest version
    docker run --rm ghcr.io/umatare5/twelvedata-exporter:latest --help

    # Specific version
    docker run --rm ghcr.io/umatare5/twelvedata-exporter:{{ .Tag }} --help

    # With environment variables
    docker run --rm -e TWELVEDATA_API_KEY ghcr.io/umatare5/twelvedata-exporter:{{ .Tag }} command
    ```

    ### 📦 Binary Installation

    ```bash
    go install github.com/umatare5/twelvedata-exporter@v{{ .Version }}
    ```

  footer: |
    **Full Changelog**: https://github.com/umatare5/twelvedata-exporter/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### 📚 Documentation

    - [README](https://github.com/umatare5/twelvedata-exporter/blob/{{ .Tag }}/README.md)
    - [Container Registry](https://github.com/umatare5/twelvedata-exporter/pkgs/container/twelvedata-exporter)

# Generate checksums for source archives
checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}_checksums.txt"

# Changelog configuration
changelog:
  use: github
  sort: asc
  abbrev: 0
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation Updates
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^Merge branch '
      - '^release:'
      - '^ci:'
      - '^test:'

# Metadata for Go proxy and pkg.go.dev
metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'
