name: actionlint

on:
  push:
    paths:
      - ".github/workflows/**"
  pull_request:
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  actionlint:
    uses: umatare5/common/.github/workflows/actionlint.yml@49d5d37a92af3d54a6aeb9e55b8ab40e3713343c # v0.10.0
