name: Release Application

on:
  push:
    branches: ["main"]
    paths: ["VERSION"]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  tagging:
    uses: umatare5/common/.github/workflows/tagging.yml@27d895ee9f1410471625dd66c22c0d63bb84b3b7 # v0.13.0

  release:
    uses: umatare5/common/.github/workflows/go-release.yml@27d895ee9f1410471625dd66c22c0d63bb84b3b7 # v0.13.0
    with:
      go_version: "1.24.5"
      goreleaser_version: "v2.11.1"
