name: Test and Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    uses: umatare5/common/.github/workflows/go-test-build.yml@49d5d37a92af3d54a6aeb9e55b8ab40e3713343c # v0.10.0
    with:
      go_version: "1.24.5"
