name: Test and Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    uses: umatare5/common/.github/workflows/go-test-build.yml@c70780f0ddb98d15dbdc6b2a89cf01f766c65b7d # v0.9.0
    with:
      go_version: "1.24.5"
