name: Prometheus Rules

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  promtool:
    uses: umatare5/common/.github/workflows/promtool.yml@9056df6d56f55ebb1866ecb9cd24b6153e5a19f8 # v0.21.1
    with:
      promtool_version: "3.14.0"
      rule_files: |
        prometheus.rules.sample.yml
      config_files: |
        prometheus.sample.yml
      lint: "all"
